[package]
name = "network-rust"
version = "0.1.0"
authors = ["Edvard Severin Pettersen <edvard.pettersen@gmail.com>"]
license = "MIT"

[lib]
name = "network_rust"
path = "src/lib.rs"

[dependencies]
lazy_static = "0.1"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"

